### PR TITLE
Add the correct links in the readme file

### PR DESCRIPTION
**Pull request by Sky0023**
Add the correct links in the readme file

### CODE REVIEW

**Comment by sishubjoshi** [comment]
Well, read the issue again #2 
The task was to just add the links and that too inside the"[name](/link/to/the)"

**Comment by Sky0023** [comment]
Okay

**Comment by sishubjoshi** [comment]
If you are participating in hacktoberfest, then it will be counted. If a PR is made then it is counted.

**Comment by Sky0023** [comment]
Okay

**Pull request closed without merging**
